<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $randomPrice =  function () {
            return round(rand(5000, 10000) / 100, 2);
        }; // 50.00 - 100.00

        $products = [
            [
                'name' =>  "Café Caramel con Chocolate",
                'price' => $randomPrice(),
                'image' => "cafe_01",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Frio con Chocolate Grande",
                'price' => $randomPrice(),
                'image' => "cafe_02",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Latte Frio con Chocolate Grande",
                'price' => $randomPrice(),
                'image' => "cafe_03",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Latte Frio con Chocolate Grande",
                'price' => $randomPrice(),
                'image' => "cafe_04",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Malteada Fria con Chocolate Grande",
                'price' => $randomPrice(),
                'image' => "cafe_05",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Mocha Caliente Chico",
                'price' => $randomPrice(),
                'image' => "cafe_06",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Mocha Caliente Grande con Chocolate",
                'price' => $randomPrice(),
                'image' => "cafe_07",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Caliente Capuchino Grande",
                'price' => $randomPrice(),
                'image' => "cafe_08",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Mocha Caliente Mediano",
                'price' => $randomPrice(),
                'image' => "cafe_09",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Mocha Frio con Caramelo Mediano",
                'price' => $randomPrice(),
                'image' => "cafe_10",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Mocha Frio con Chocolate Mediano",
                'price' => $randomPrice(),
                'image' => "cafe_11",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Espresso",
                'price' => $randomPrice(),
                'image' => "cafe_12",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Capuchino Grande con Caramelo",
                'price' => $randomPrice(),
                'image' => "cafe_13",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Café Caramelo Grande",
                'price' => $randomPrice(),
                'image' => "cafe_14",
                'categoryId' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 3 donas de Chocolate",
                'price' => $randomPrice(),
                'image' => "donas_01",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 3 donas Glaseadas",
                'price' => $randomPrice(),
                'image' => "donas_02",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Dona de Fresa",
                'price' => $randomPrice(),
                'image' => "donas_03",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Dona con Galleta de Chocolate",
                'price' => $randomPrice(),
                'image' => "donas_04",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Dona glass con Chispas Sabor Fresa",
                'price' => $randomPrice(),
                'image' => "donas_05",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Dona glass con Chocolate",
                'price' => $randomPrice(),
                'image' => "donas_06",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Dona de Chocolate con MÁS Chocolate",
                'price' => $randomPrice(),
                'image' => "donas_07",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 3 donas de Chocolate",
                'price' => $randomPrice(),
                'image' => "donas_08",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 3 donas con Vainilla y Chocolate",
                'price' => $randomPrice(),
                'image' => "donas_09",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 6 Donas",
                'price' => $randomPrice(),
                'image' => "donas_10",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 3 Variadas",
                'price' => $randomPrice(),
                'image' => "donas_11",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Dona Natural con Chocolate",
                'price' => $randomPrice(),
                'image' => "donas_12",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 3 Donas de Chocolate con Chispas",
                'price' => $randomPrice(),
                'image' => "donas_13",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Dona Chocolate y Coco",
                'price' => $randomPrice(),
                'image' => "donas_14",
                'categoryId' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete Galletas de Chocolate",
                'price' => $randomPrice(),
                'image' => "galletas_01",
                'categoryId' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete Galletas de Chocolate y Avena",
                'price' => $randomPrice(),
                'image' => "galletas_02",
                'categoryId' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de Muffins de Vainilla",
                'price' => $randomPrice(),
                'image' => "galletas_03",
                'categoryId' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete de 4 Galletas de Avena",
                'price' => $randomPrice(),
                'image' => "galletas_04",
                'categoryId' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Galletas de Mantequilla Variadas",
                'price' => $randomPrice(),
                'image' => "galletas_05",
                'categoryId' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Galletas de sabores frutales",
                'price' => $randomPrice(),
                'image' => "galletas_06",
                'categoryId' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Hamburguesa Sencilla",
                'price' => $randomPrice(),
                'image' => "hamburguesas_01",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Hamburguesa de Pollo",
                'price' => $randomPrice(),
                'image' => "hamburguesas_02",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Hamburguesa de Pollo y Chili",
                'price' => $randomPrice(),
                'image' => "hamburguesas_03",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Hamburguesa Queso y Pepinos",
                'price' => $randomPrice(),
                'image' => "hamburguesas_04",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Hamburguesa Cuarto de Libra",
                'price' => $randomPrice(),
                'image' => "hamburguesas_05",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Hamburguesa Doble Queso",
                'price' => $randomPrice(),
                'image' => "hamburguesas_06",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Hot Dog Especial",
                'price' => $randomPrice(),
                'image' => "hamburguesas_07",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Paquete 2 Hot Dogs",
                'price' => $randomPrice(),
                'image' => "hamburguesas_08",
                'categoryId' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "4 Rebanadas de Pay de Queso",
                'price' => $randomPrice(),
                'image' => "pastel_01",
                'categoryId' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Waffle Especial",
                'price' => $randomPrice(),
                'image' => "pastel_02",
                'categoryId' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Croissants De la casa",
                'price' => $randomPrice(),
                'image' => "pastel_03",
                'categoryId' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pay de Queso",
                'price' => $randomPrice(),
                'image' => "pastel_04",
                'categoryId' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pastel de Chocolate",
                'price' => $randomPrice(),
                'image' => "pastel_05",
                'categoryId' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Rebanada Pastel de Chocolate",
                'price' => $randomPrice(),
                'image' => "pastel_06",
                'categoryId' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Spicy con Doble Queso",
                'price' => $randomPrice(),
                'image' => "pizzas_01",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Jamón y Queso",
                'price' => $randomPrice(),
                'image' => "pizzas_02",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Doble Queso",
                'price' => $randomPrice(),
                'image' => "pizzas_03",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Especial de la Casa",
                'price' => $randomPrice(),
                'image' => "pizzas_04",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Chorizo",
                'price' => $randomPrice(),
                'image' => "pizzas_05",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Hawaiana",
                'price' => $randomPrice(),
                'image' => "pizzas_06",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Tocino",
                'price' => $randomPrice(),
                'image' => "pizzas_07",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Vegetales y Queso",
                'price' => $randomPrice(),
                'image' => "pizzas_08",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Pepperoni y Queso",
                'price' => $randomPrice(),
                'image' => "pizzas_09",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Aceitunas y Queso",
                'price' => $randomPrice(),
                'image' => "pizzas_10",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' =>  "Pizza Queso, Jamón y Champiñones",
                'price' => $randomPrice(),
                'image' => "pizzas_11",
                'categoryId' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        DB::table('products')->insert($products);
    }
}
